name: C Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install build-essential make

    - name: Build project
      working-directory: ./Part-1
      run: make

    - name: Run tests
      working-directory: ./Part-1
      run: make test

    - name: Clean up
      working-directory: ./Part-1
      run: make clean
